server:
  port: 1025
  servlet:
    context-path: /exam
spring:
  application:
    name: exam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC